#!/bin/bash

#DO NOT CHANGE ANYTHING BELOW
###################################
cfg_file="/opt/loxberry/config/plugins/mirobot2lox/mi.cfg"
path="/opt/loxberry/data/plugins/mirobot2lox"
name="mirobo_2_lox_gsd"
name1="mirobo2lox"
sed -i 's/;/#/' $cfg_file
source $cfg_file
LOGFILE="/opt/loxberry/log/plugins/mirobot2lox/mirobot2lox.log"
timestamp_1=$(date +%s -r $cfg_file)

if [ "$LOOPTIME" == "" ]; then  LOOPTIME="20"; fi
if [ "$DEBUG" == "" ]; then  DEBUG="1"; fi

#LOOP
i=0
while true
do
D=`date "+%b %d %H:%M:%S"`

while [ $i -eq 0 ] 
do

timestamp_2=$(date +%s -r $cfg_file)
if [ "$timestamp_1" != "$timestamp_2" ]; then
echo "$D Service $name1 wurde durch Config-Watchdog neu gestartet" >> $LOGFILE
service mirobo2lox restart
fi

#get data an send 2 loxone
if [ "$R1_ACTIVE" == "1" ]; then
D=`date "+%b %d %H:%M:%S"`
$path/$name 1 >/dev/null 2>&1 &
sleep 0.2
if [ "$DEBUG" == "1" ]; then
echo "$D GSD Robot 1 wird ausgeführt" >> $LOGFILE
fi
fi

if [ "$R2_ACTIVE" == "1" ]; then
D=`date "+%b %d %H:%M:%S"`
$path/$name 2 >/dev/null 2>&1 &
sleep 0.2
if [ "$DEBUG" == "1" ]; then
echo "$D GSD Robot 2 wird ausgeführt" >> $LOGFILE

fi
fi
if [ "$R3_ACTIVE" == "1" ]; then
D=`date "+%b %d %H:%M:%S"`
$path/$name 3 >/dev/null 2>&1 &
sleep 0.2
if [ "$DEBUG" == "1" ]; then
echo "$D GSD Robot 3 wird ausgeführt" >> $LOGFILE

fi
fi
i=$[LOOPTIME]
  done
sleep 1
  ((i--))
done